### ISSUE TITLE
Error parsing some FLAC files

### ISSUE THREAD

**Issue by hvianna** [Borewit/audio-tag-analyzer#21]
I just noticed this issue with music-metadata-browser where it fails to parse some FLAC files and throws the error message `TypeError: e is undefined`. Tried it here on audio-tag-analyzer and got the same result.

Is there any way I can send you one of the offending files privately, since it's an encode of a commercial album?

Thanks!

Blocked by: [music-metadata-browser#62](https://github.com/Borewit/music-metadata-browser/pull/62)

**Comment by Borewit** [comment]
I will look into it. Can you contact me via [chat](https://discord.gg/KyBr6sb) @hvianna?

**Comment by Borewit** [comment]
I love your project, I would like to include [audioMotion](https://hvianna.github.io/audioMotion.js/public/) in the online demo list of [music-metadata-browser](https://github.com/Borewit/music-metadata-browser).

Created: [PR music-metadata-browser#61: _Add audioMotion to online-demo list_](https://github.com/Borewit/music-metadata-browser/pull/61)

**Comment by hvianna** [comment]
Thank you! I would love to have audioMotion featured on music-metadata-browser, that would be awesome!!

**Comment by Borewit** [comment]
Based by https://github.com/Borewit/music-metadata-browser/issues/62, which is caused by https://github.com/Borewit/music-metadata/issues/266

**Comment by Borewit** [comment]
I think the way one of the two pictures is embedded in the FLAC file is wrong, nevertheless, it is now supported in [v0.5.6](https://github.com/Borewit/audio-tag-analyzer/releases/tag/v0.5.6)
