### ISSUE TITLE
error in parsing .ogg file

### ISSUE THREAD

**Issue by Patrick-web** [Borewit/audio-tag-analyzer#278]
I'm getting this error when trying to parse a .ogg file
>Failed to parse Midnight Stroll - Ghostrifter Official [Vlog No Copyright Music]_48k.ogg. Error message: FourCC contains invalid characters: 1a 45 df a3.

I'm unable attach the specific file as github does not support the file type

**Comment by Borewit** [comment]
Thanks for your issue.

> I'm unable attach the specific file as github does not support the file type

The trick is to zip it first.
