### ISSUE TITLE
Failed to parse aiff files

### ISSUE THREAD

**Issue by raikusy** [Borewit/audio-tag-analyzer#345]
I was trying to get metadata from a aiff file from [https://audio-tag-analyzer.netlify.app/](https://audio-tag-analyzer.netlify.app/) But it fails showing the following error:

> Failed to parse 09 - No Sanctuary Here.aiff.
> 
> Error message: FourCC contains invalid characters: 28 63 29 20.
> 
> If you believe this is a bug, please open an issue here.
> Don't forget to attach the audio file which could not be parsed.

[music-metadata](https://github.com/Borewit/music-metadata) package throws the same error for aiff files.

[Link to the audio file](https://rr-s3.ovechr.com/local/audio/aiff/05c5e92e-2c8a-4954-85c0-fe0ca1385254_09_-_No_Sanctuary_Here.aiff)

**Comment by Borewit** [comment]
Blocked by Borewit/music-metadata#643.

**Comment by Borewit** [comment]
#354 should fix the issue.
