### ISSUE TITLE
Icon broken

### ISSUE THREAD

**Issue by Borewit** [Borewit/audio-tag-analyzer#406]
![icon-broken](https://user-images.githubusercontent.com/23255260/104232817-284ab180-5451-11eb-97a9-b6b55251de07.png)

**Comment by claudioantonio** [comment]
I found this issue at https://goodfirstissues.com/
I´m looking for open projects with good first issues in open state to practice TypeScript.
May I try fix it?

**Comment by Borewit** [comment]
Please do @claudioantonio.

This project is a demo for  [music-metadata-browser](https://github.com/Borewit/music-metadata-browser), [music-metadata](https://github.com/Borewit/music-metadata). You can find a list of audio logo's there. If you a better idea how to do the look and feel I am also open to it.

Maybe also goot to know there are also a bunch of sub components I maintain, all written TypeScript:
![music-metadata-browser dependencies](https://user-images.githubusercontent.com/23255260/104290878-2a495a80-54bb-11eb-9477-f300bab21f57.png)

**Comment by claudioantonio** [comment]
@Borewit the image address for this icon is not valid anymore, as You can see in the image below.
Is there any other location for this icon?

![broken link](https://user-images.githubusercontent.com/12503122/104304397-134e3c80-54aa-11eb-899f-6e3f0fa04c14.png)

**Comment by Borewit** [comment]
Check: https://github.com/Borewit/music-metadata/blob/master/README.md. If it not part that I do not know an alternative location. You can take out, pick another one. The logo's are just there to give impression what kind of formats are supported.
